server:
  port: 8085

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    provision-service:
      path: /m2/**
      serviceId: provision-service
      strip-prefix: true
      #url: http://localhost:8082/
    cont-service:
      path: /m1/**
      serviceId:  cont-service
      strip-prefix: true
      #url: http://localhost:8081/
    cert-service:
      path: /m3/**
      serviceId:  cert-service
      strip-prefix: true
      #url: http://localhost:8080/
    zuulserver:
      path: /gateway/**
      serviceId:  zuulserver
      strip-prefix: true
      
ribbon:
  eureka:
    enabled: false
    
    
provision-service: 
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://provision-service.userv.svc:8082/
    ConnectTimeout: 100
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    
cont-service: 
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://contable-service.userv.svc:8081/
    ConnectTimeout: 100
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
    
cert-service: 
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://cert-service.userv.svc:8080/
    ConnectTimeout: 100
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

