server:
  port: 8085
  
spring:
  application:
    name: zuulserver
    
zuul:
  prefix: /api
  routes:
    provision-service:
      path: /micro2/**
      #url: http://prov-service-adifv2.apps.okd.openshifthub.ml/adif/
      serviceId: provision-service
    cont-service:
      path: /micro1/**
      #url: http://cont-service-adifv2.apps.okd.openshifthub.ml/adif/
      serviceId: cont-service
    cert-service:
      path: /micro3/**
      #url: http://cert-service-adifv2.apps.okd.openshifthub.ml/adif/
      serviceId: cert-service
    
endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false
    
eureka:
  instance:
    port: 8761
    
eureka:
  instance:
    hostname: circuit-breaker.adifv2.svc
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    













